# Generated by Django 5.1.4 on 2025-01-11 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='short_code',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='short_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analytics',
            name='shortened_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.shortenedurl'),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
